CREATE SEQUENCE SEQ_FRAMEWORK_SYS_MENU AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_SYS_PERMISSION AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_SYS_ROLE AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_USER_ROLE AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_PERM_ASSIGN AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_USER_INF AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

CREATE SEQUENCE SEQ_FRAMEWORK_ACTION_LOG AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 20 NO CYCLE NO ORDER;   

